services:
  bun-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5847:5000"
    env_file:
      - .env.docker
    volumes:
      - .:/usr/src/app
    user: "bun"
